theme: jekyll-theme-minimal
title: Welcome to Lianqi's Page
description: For MAOS and sandom computing tips
permalink: /:year/:month/:title/
gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
