# Permalinks
permalink:        pretty

# Setup
title:            MAOS
tagline:          'Tips'
description:      'Computing Tips'
url:              https://lianqiw.github.io
baseurl:          https://lianqiw.github.io/

author:
  name:           'Lianqi Wang'
  url:            https://lianqiw.github.com

paginate:         5

# Custom vars
version:          2.2-r2

github:
  repo:           https://github.com/lianqiw/maos
